### ISSUE TITLE
Konzept - grobes, skizzenhaftes , aus dem Struktur und Layout, als auch das Interaktionsverhalten Ihrer Lösung hervorgehen

### ISSUE THREAD

**Issue by mfe-** [mfe-/Interface-und-Interaction-Design#1]
Erstellen ein grobes, skizzenhaftes Konzept, aus dem Struktur und Layout, als auch das Interaktionsverhalten Ihrer Lösung hervorgehen.

Achten Sie darauf, dass Sie sich nicht zu sehr in graphischen Details verlieren – im Vordergrund steht der strukturelle Aufbau Ihrer Lösung und ein
durchdachtes Interaktionskonzept.

**Comment by Claudia55** [comment]
Mockups für graphische Darstellung

**Comment by Claudia55** [comment]
![bsp3 mockups](https://cloud.githubusercontent.com/assets/24211594/21061907/b7ac644c-be4e-11e6-9d09-3fa65f55f5b9.png)

**Comment by mfe-** [comment]
Schaut gut aus 👍 

Ein paar Anmerkungen:

- Wenn man die Applikation startet, sieht man zu Beginn die Login- & Registriermaske. 
Die Registriermaske würde ich auf eine separate Seite auslagern, da man doch einige Daten angeben muss (U.a. auch ein persönliches Profilbild, Angaben ob man gehandicapt ist, zu welcher Zielgruppe man gehört (Hilfsgebend/suchend), besondere Merkmale usw. uswf. Bitte in #12 und #8 berücksichtigen; 
- Auf der Startseite würde ich statt den Gruppenaufträgen die letzten Bewertungen anzeigen die der User abgegeben hat #2 
- Community verwalten - sieht das nur der Administrator? Falls ja, würde ich den Punkt weglassen da nicht in der Übungsangabe gefordert und wir uns somit Arbeit ersparen können
- Anfrage vs Angebot- hier wäre die Frage, ob man das Menü "Hilfe geben" bzw. "Hilfe suchen" für die jweilige Zielgruppe ausblendet. Uhrzeitangabe sollte auch noch dabei sein. Ich denke, dass die Hilfsanfragen eher für kurzfristig Leistungen gedacht sind.  Weitere Details siehe auch #5 
- Leistung Bewerten müssen wir noch dazugeben

@Claudia55 Kannst du bitte die Datei hochladen die das Tool erstellt hat (wie heißt das nochmal?), dann können wir diese auch bearbeiten 😃

**Comment by seinep** [comment]
Welche tool verwendest du für die Mockups?

**Comment by mfe-** [comment]
@seinep Sie verwendet, wenn ich mich nicht irre, Viso. Vlt. gibts die Software [hier](http://www.informatik.tuwien.ac.at/aktuelles/87).

**Comment by seinep** [comment]
It's Visio. Danke=)

**Comment by Claudia55** [comment]
ja ich hab auch Visio verwendet ;) Und für Mockups Balsamiq Mockups 3

**Comment by mfe-** [comment]
[Storyboard für Looking for Assistance and Helpers](https://github.com/mfe-/Interface-und-Interaction-Design/blob/master/bsp3/Draft.jpg)
