### ISSUE TITLE
Prototyp / Login

### ISSUE THREAD

**Issue by mfe-** [mfe-/Interface-und-Interaction-Design#13]

**Comment by ghost** [comment]
Hallo ich werde mich für die Login und Registrierung kümmern. Dafür brauche ich den Name dieses Apps früh wie möglich so kann ich auch ein geeignetes Logo heraussuchen.

**Comment by ghost** [comment]
Hintergrund bald : Werde mit Photoshop gemacht. 
Farbe : Orange/Rot ( Auch als Toolbar mit dem Name des Apps für die anderen Seiten zu benützten)
Reference: 
HEX #f85e56, RGB(248,94,86), CMYK(0,62,65,3)
Schrift : Open Sans (Regulär or Light Italic) or Lato (Light or Regular)
Schrift Name for App (under the logo) : Ubuntu Medium
Link: Open sans
https://www.fontsquirrel.com/fonts/open-sans
Link: Lato
https://www.fontsquirrel.com/fonts/lato
Link: Ubuntu
https://www.fontsquirrel.com/fonts/ubuntu

**Comment by mfe-** [comment]
Appname und Logo wurde noch nicht festgelegt du kannst dir also einen Aussuchen. (oder einen Platzhalter dafür erstellen)

Die Schriftart bitte auch gleich im CSS definieren, damit wir diese bei den anderen Prototype Issues verwenden können.

**Comment by ghost** [comment]
Ok mach das...noch eine Frage..ihr programmiert in Bootstrap oder benützt ihr den Tool (bootstrapstudio.io) ?

**Comment by ghost** [comment]
Schrift in CSS : 
Für die Titeln : h1 {
	font-family: 'PT Sans Caption';
	font-size: 12px;
	font-style: normal;
	font-variant: normal;
	font-weight: 400;
	line-height: 40px;
}
//Grösse des Schrittes nach eure Wahl (= font-size)

Für den anderen Text : h2 {
	font-family: 'Quattrocento Sans';
	font-size: 30px;
	font-style: normal;
	font-variant: normal;
	font-weight: 400;
	line-height: 9px;

**Comment by mfe-** [comment]
@galla1993 Laut Angabe sollen wir Bootstrap verwenden (siehe [#3](https://github.com/mfe-/Interface-und-Interaction-Design/issues/3#issuecomment-263143539) ). Ich denke es spricht nichts dagegen wenn jeder mit seinem bevorzugen Tool arbeitet, wenn dabei eine html/css File rauskommt.

**Comment by mfe-** [comment]
Bzw. Ich habe die passende [CSS File](https://github.com/mfe-/Interface-und-Interaction-Design/blob/97ba33560cc938cbe29e4d921b67824fb77b4bcd/bsp3/index.css) gerade angelegt und hochgeladen damit jeder diese verwenden kann. Mit einem `git pull` habe ihr dann die Files.

**Comment by ghost** [comment]
Hab den file gepusht...hab gesehen dass mein teil schon gemacht worden ist...was bedeutet das sorry? auf jeden fall hab schon meins auf deins aufgepasst

**Comment by mfe-** [comment]
@galla1993 Ich habe nur schnell eine Login Maske rein gegeben damit man zumindest mal die wichtigsten Seiten erreichen kann. Du kannst von meinem oder deinem Stand weiter arbeiten.

Ich würde sagen, wir sollten schauen, dass zumindest alle notwendigen Masken und Seiten als erstes erstellt werden. Designtechnische Verbesserungen können wir einbringen, wenn noch Zeit vorhanden ist.
Also vorläufig die Default Bootstrap Styles verwenden und dann wenn wir fertig sind das Design anpassen.

**Comment by ghost** [comment]
Ahh soo perfekt vielen dank für den Ansatz:)
Ich bin auch mit meinen Teilen (=Login-Registrierung )schon soweit....hab nur a kleinen Fehler (=bei der Registrierung) den ich noch fixieren muss aber sonst bin i fertig und hab schon gepusht so könnte ihr das auch noch schauen.
Wenn es fehlt kann ich noch die Startseite machen. Kein Problem und für die andere Teile können wir auch morgen den Design anzupassen. Es wird sicherlich nicht so viel Zeit nehmen.

**Comment by mfe-** [comment]
@galla1993 Ok gut, aber für die Registrierung gibt es eine eigene Issue die ich bereits bearbeite :) Siehe #4 
Ich gebe dir bescheid, wenn ich fertig bin. Dann kannst du das Design nochmal überarbeiten. Nicht, dass wir die Arbeit doppelt machen ;)

**Comment by ghost** [comment]
uuupps zu spät hatte nur jetzt das gelesen sorry .-.

**Comment by ghost** [comment]
schau dich an was hab ich gemacht und entschiede ob es passt oder nicht ..Es tut mir leid hab komplett übersehen
