### ISSUE TITLE
Prototype / Profilseite 

### ISSUE THREAD

**Issue by Claudia55** [mfe-/Interface-und-Interaction-Design#16]
Seite, welche Daten des Benutzers beinhaltet.

**Comment by Claudia55** [comment]
Seite erstellt und funktionstüchtig.

**Comment by mfe-** [comment]
Ich habe die Editionsmöglichkeit von Vor/Nachname, Email,Adresse entfernt. Ansonsten würde die Identifikation über die Handysignatur nichts bringen, wenn man nachher Name usw. wieder ändern kann.
